version: '3.11'

x-image: &image rabbitmq:3.11-management

x-common-mounts: &common-mounts
  - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
  - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
  - "./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh"

x-caps: &caps
  - NET_ADMIN
  - NET_RAW
  - SYS_PTRACE

x-entrypoint: &entrypoint "/usr/local/bin/cluster-entrypoint.sh"

services:
  rabbitmq1:
    image: *image
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    cap_add:
      *caps
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint:
      *entrypoint

  rabbitmq2:
    image: *image
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit@rabbitmq2.log
    cap_add:
      *caps
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint:
      *entrypoint

  rabbitmq3:
    image: *image
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit@rabbitmq3.log
    cap_add:
      *caps
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint:
      *entrypoint

  rabbitmq4:
    image: *image
    hostname: rabbitmq4
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit@rabbitmq4.log
    cap_add:
      *caps
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint:
      *entrypoint

  rabbitmq5:
    image: *image
    hostname: rabbitmq5
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit@rabbitmq5.log
    cap_add:
      *caps
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint:
      *entrypoint

  haproxy:
    image: haproxy:2.4
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
      - rabbitmq4
      - rabbitmq5
    ports:
      - 15672:15672
      - 5672:5672

